#!/bin/sh

echo "running chown and chmod on chfilter"

chown root:wheel /usr/bin/chfilter
chmod 6755 /usr/bin/chfilter

echo "restoring filter file"

mv /Library/MobileSubstrate/DynamicLibraries/NoClipboardForYou.plist.bak /Library/MobileSubstrate/DynamicLibraries/NoClipboardForYou.plist