#!/bin/sh

if [ -e /Library/MobileSubstrate/DynamicLibraries/NoClipboardForYou.plist ]; then
    echo "backing up filter file"

    mv /Library/MobileSubstrate/DynamicLibraries/NoClipboardForYou.plist /Library/MobileSubstrate/DynamicLibraries/NoClipboardForYou.plist.bak
fi